name: 'Create Pull Request'

description: 'Create PR with dependency updates'

inputs:
  token:
    required: true
    type: string
    description: 'GitHub token'

  base-branch:
    required: true
    type: string
    description: 'Base branch for PR'
    default: 'develop'

  branch-prefix:
    required: true
    type: string
    description: 'Prefix for new branch'
    default: 'update-dependencies'

  files:
    required: true
    type: string
    description: 'Files to commit'

  commit-message:
    required: true
    type: string
    description: 'Message the commit will have'
    default: ''

  pr-title:
    required: true
    type: string
    description: 'Title of the pull request'
    default: ''

  pr-body:
    required: true
    type: string
    description: 'The Markdown-supported body for the Github pull request'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Create and push branch
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        BRANCH_NAME="${{ inputs.branch-prefix }}-$(date +%Y%m%d)-${{ github.run_id }}"
        echo "::debug::Creating branch: $BRANCH_NAME"
        git checkout -b "$BRANCH_NAME"
        git add ${{ inputs.files }}
        git commit -m "${{ inputs.commit-message }}"
        git push --force origin "$BRANCH_NAME"
        
        # Set branch name for next step
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Create Pull Request
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        echo "::debug::Creating pull request from $BRANCH_NAME to ${{ inputs.base-branch }}"
        gh pr create \
          --title "${{ inputs.pr-title }}" \
          --body "${{ inputs.pr-body }}" \
          --head "$BRANCH_NAME" \
          --base "${{ inputs.base-branch }}"
