name: 'Enable Pull Request Automerge'
description: 'A GitHub action to enable auto-merge on a pull request'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
  repository:
    description: 'The target GitHub repository containing the pull request'
    default: ${{ github.repository }}
  pull-request-number:
    description: 'The number of the target pull request'
    required: true
  merge-method:
    description: 'The merge method to use. `merge`, `rebase` or `squash`.'
    default: merge
runs:
  using: composite
  steps:
    - name: Validate and enable automerge
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPOSITORY: ${{ inputs.repository }}
        PR_NUMBER: ${{ inputs.pull-request-number }}
        MERGE_METHOD: ${{ inputs.merge-method }}
      run: |
        METHOD=$(echo "$MERGE_METHOD" | tr '[:upper:]' '[:lower:]')

        if [[ "$METHOD" != "merge" && "$METHOD" != "rebase" && "$METHOD" != "squash" ]]; then
          echo "::error::Invalid merge method '$METHOD'. Must be one of: merge, rebase, squash."
          exit 1
        fi

        gh pr merge -R "$REPOSITORY" --"$METHOD" --auto "$PR_NUMBER"
