name: 'Enable Pull Request Automerge'
description: 'A GitHub action to enable auto-merge on a pull request'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
  repository:
    description: 'The target GitHub repository containing the pull request'
    default: ${{ github.repository }}
  pull-request-number:
    description: 'The number of the target pull request'
    required: true
runs:
  using: composite
  steps:
    - name: Enable automerge
      shell: bash
      run: gh pr merge -R "${{ inputs.repository }}" --merge --auto "${{ inputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ inputs.token }}
