name: 'Check Changes'

description: 'Check if specified files have changes'

inputs:
  files:
    required: true
    type: string
    default: ''
    description: 'Space-separated list of files to check'

outputs:
  has_changes:
    description: 'Whether files have changed (true/false)'
    value: ${{ steps.check_changes.outputs.has_changes }}

runs:
  using: 'composite'
  steps:
    - name: Check for changes
      id: check_changes
      shell: bash
      run: |
        FILES="${{ inputs.files }}"
        
        echo "::debug::Checking for changes in files: $FILES"
        
        # Use -- to separate revisions from pathspecs for safety.
        DIFF_OUTPUT=$(git diff -- $FILES)
        if [ -z "$DIFF_OUTPUT" ]; then
          echo "::debug::No changes detected"
          echo "has_changes=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "::debug::Changes detected"
        echo "has_changes=true" >> $GITHUB_OUTPUT
