name: 'Semantic Release'

description: 'Run semantic-release with caching and optional backmerge support'

inputs:
  token:
    required: true
    description: 'GitHub token for authentication'
    default: ${{ github.token }}

  enable-backmerge:
    required: false
    description: 'Enable backmerge from main to develop after release'
    default: 'false'

  backmerge-target-branch:
    required: false
    description: 'Target branch for backmerge (only used when enable-backmerge is true)'
    default: 'develop'

  source-branch:
    required: false
    description: 'Source branch for semantic-release (typically main)'
    default: 'main'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        fetch-tags: true
        token: ${{ inputs.token }}

    - name: Cache semantic-release
      id: cache-sr
      uses: actions/cache@v5
      with:
        path: ~/.npm-global
        key: "npm-sr-${{ runner.os }}-${{ hashFiles('*releaserc*', '**/package-lock.json', '**/package.json') }}"
        restore-keys: |
          npm-sr-${{ runner.os }}-

    - name: Install semantic-release and plugins
      if: steps.cache-sr.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npm config set prefix ~/.npm-global

        # Extract plugin names from .releaserc
        PLUGINS=$(jq -r '.plugins[] | if type == "string" then . else .[0] end' .releaserc* 2>/dev/null || echo "")

        # Build install arguments safely without eval
        INSTALL_ARGS="semantic-release"
        if [ -n "$PLUGINS" ]; then
          while IFS= read -r plugin; do
            # Skip empty lines
            [ -z "$plugin" ] && continue
            INSTALL_ARGS="$INSTALL_ARGS $plugin"
          done <<< "$PLUGINS"
        fi

        # Install using xargs to avoid eval
        echo "$INSTALL_ARGS" | xargs npm install -g

    - name: Add ~/.npm-global/bin to PATH
      shell: bash
      run: echo "~/.npm-global/bin" >> $GITHUB_PATH

    - name: Run semantic-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: semantic-release

    - name: Backmerge to develop
      if: inputs.enable-backmerge == 'true' && github.ref == format('refs/heads/{0}', inputs.source-branch)
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        TARGET_BRANCH: ${{ inputs.backmerge-target-branch }}
        SOURCE_BRANCH: ${{ inputs.source-branch }}
      run: |
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git fetch origin "$TARGET_BRANCH"
        git checkout "$TARGET_BRANCH"

        if ! git merge "$SOURCE_BRANCH" --no-ff -m "chore: backmerge $SOURCE_BRANCH after release"; then
          echo "::error::Merge conflict detected when backmerging $SOURCE_BRANCH into $TARGET_BRANCH. Please resolve manually."
          git merge --abort
          exit 1
        fi

        git push origin "$TARGET_BRANCH"
