name: 'Checkout and Setup'

description: 'Common checkout and git configuration'

inputs:
  token:
    required: true
    description: 'GitHub token'
    default: ${{ github.token }}

  app-slug:
    required: false
    description: 'GitHub App slug (e.g., my-app). If provided, configures git as the app bot instead of default user'
    default: ''

  shallow:
    required: false
    description: 'If true, performs shallow checkout. If false, fetches full history with tags'
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository (shallow)
      if: ${{ inputs.shallow == 'true' }}
      uses: actions/checkout@v6
      with:
        token: ${{ inputs.token }}

    - name: Checkout repository (full history)
      if: ${{ inputs.shallow == 'false' }}
      uses: actions/checkout@v6
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0
        fetch-tags: true

    - name: Configure git (as an app)
      if: ${{ inputs.app-slug != '' }}
      shell: bash
      env:
        APP_SLUG: ${{ inputs.app-slug }}
      run: |
        bot_login="${APP_SLUG}[bot]"
        # URL-encode [] as %5B %5D
        response=$(curl -fsSL "https://api.github.com/users/${APP_SLUG}%5Bbot%5D")
        bot_id=$(echo "$response" | jq -r .id)

        if [ -z "$bot_id" ] || [ "$bot_id" = "null" ]; then
          echo "::error::Failed to resolve bot ID for app slug '${APP_SLUG}'. API response: $response"
          exit 1
        fi

        git config --local user.name "$bot_login"
        git config --local user.email "${bot_id}+${bot_login}@users.noreply.github.com"

    - name: Configure git (as default actions user)
      if: ${{ inputs.app-slug == '' }}
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
