name: 'Checkout and Setup'

description: 'Common checkout and git configuration'

inputs:
  token:
    required: true
    description: 'GitHub token'
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}

    - name: Configure Git
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
