name: Update GitHub Actions
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight

jobs:
  update-actions:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Create temporary GitHub App Token
        id: app
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.HOUSEKEEPING_BOT_APP_ID }}
          private-key: ${{ secrets.HOUSEKEEPING_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}

      - name: Update GitHub Actions
        uses: alchemaxinc/update-deps/actions@v1
        with:
          token: ${{ steps.app.outputs.token }}
          auto-merge: 'true'
          base-branch: 'main'
          prefixes: 'actions'
          file-glob: '.github/**/*.{yml,yaml}'
          branch-prefix: 'update-actions'
          pr-title: 'chore: Update GitHub Actions'
          commit-message: 'chore: update github actions'

      - name: Update GitHub Actions (files in top-level non-hidden folders)
        uses: alchemaxinc/update-deps/actions@v1
        with:
          token: ${{ steps.app.outputs.token }}
          base-branch: 'main'
          branch-prefix: 'update-action-manifests'
          pr-title: 'fix: update `action.yml` files'
          commit-message: 'fix: update `action.yml` files'
          file-glob: '[!.]*/action.{yml,yaml}'
          check-files: '[!.]*/action.{yml,yaml}'
          prefixes: 'actions,hashicorp'
          auto-merge: 'true'
